### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by uDude**
Attachment support with rudimentary test functions.  TODO: basic auth test functions and perhaps some more error cases.

### CODE REVIEW

**Comment by uDude** [comment]
I have all tests succeeding, what could be the difference?

**Comment by mkrogemann** [comment]
Hey @uDude 
Sorry for responding with such long delay.
One thing that we need to clean up: Your pull request contains conflicts, as far as I can see from the github visualization.
Can you please try to rebase your branch against the current master and see if things work then?

**Comment by uDude** [comment]
The problem was that I did my work against 1.4.3.  There are enough changes
going to 1.5 that I need to to do just as you say.

**Comment by mkrogemann** [comment]
This has not moved forward and I will close it for now. Please feel free to submit another issue or PR @uDude

**Pull request closed without merging**
